name: "PR size labeler"
on: [pull_request]

jobs:
  changed-lines-count-labeler:
    runs-on: ubuntu-latest
    name: Automatically labelling pull requests based on the changed lines count
    steps:
    - name: Set a label
      uses: vkirilichev/changed-lines-count-labeler@v0.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/changed-lines-count-labeler.yml
